### ISSUE TITLE
autodiff

### ISSUE THREAD

**Issue by mlubin** [matthieugomez/LeastSquaresOptim.jl#1]
Cool that AD is hooked up! You may want to look at the ForwardDiff package instead of DualNumbers. In addition to having automatic routines that replace the ``autodiff.jl`` file here, it's also generally [faster](https://github.com/jrevels/julialang.github.com/blob/master/blog/_posts/2015-09-27-auto-diff-in-julia.md).
CC @jrevels

**Comment by matthieugomez** [comment]
Yep, I just used your pull request in NLsolve

I've just tried `ForwardDiff`

The [autodiff tests](https://github.com/matthieugomez/LeastSquaresOptim.jl/blob/master/test/nonlinearleastsquares.jl#L556)are currently passed in 0.5 sec.

Replacing autodiff.jl by
```julia
using ForwardDiff
function LeastSquaresProblem(x::Vector, y::Vector, f!::Function, J::Matrix)
    permf!(yp::Vector, xp::Vector) = f!(xp, yp)
    permg! = ForwardDiff.jacobian(permf!, mutates = true, chunk_size = 1, output_length = length(y))
    g!(xp::Vector, Jp::Matrix) = permg!(Jp, xp)
    LeastSquaresProblem(x, y, f!, J, g!)
end
```
They now pass in  2.492898 seconds (4.73 M allocations: 171.238 MB, 1.15% gc time). Thoughts?

**Comment by matthieugomez** [comment]
Actually when repeating the test (ie removing compilation), I get 0.1 in both cases.
