### ISSUE TITLE
Ambiguity errors from new matrix multiplication methods in LinearAlgebra

### ISSUE THREAD

**Issue by andreasnoack** [matthieugomez/LeastSquaresOptim.jl#16]
The methods in https://github.com/matthieugomez/LeastSquaresOptim.jl/blob/c0047cbef9d7bc021f2877ac650404c1bd337df0/src/utils/lsmr.jl#L16-L21 need to be behind a conditions similarly to https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/blob/1ac7a0f83121849efd76715ee85a115047d6468d/src/juliaBLAS.jl#L87 to avoid breakage in the upcoming Julia version 1.3.

**Comment by matthieugomez** [comment]
Solved & tagged a new version. Thanks!
