### ISSUE TITLE
QR not defined

### ISSUE THREAD

**Issue by finmod** [matthieugomez/LeastSquaresOptim.jl#3]
Just discovering LeastSquaresOptim as an alternative to pysparselm. 
Running the tests, I encounter the following error:

Running tests:
	FAILED: nonlinearsolvers.jl
LoadError: UndefVarError: QR not defined
 [inlined code] from C:\Users\Denis\Documents\Finmod\Schumann Bischoff\LeastSquaresOptim.jl-master\test\runtests.jl:13
 in anonymous at no file:0
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in include_string at loading.jl:282
 in execute_request_0x535c5df2 at C:\Users\Denis\.julia\v0.4\IJulia\src\execute_request.jl:183
 in eventloop at C:\Users\Denis\.julia\v0.4\IJulia\src\IJulia.jl:143
 in anonymous at task.jl:447
while loading C:\Users\Denis\Documents\Finmod\Schumann Bischoff\LeastSquaresOptim.jl-master\test\nonlinearsolvers.jl, in expression starting on line 505
LoadError: LoadError: LoadError: UndefVarError: QR not defined
while loading C:\Users\Denis\Documents\Finmod\Schumann Bischoff\LeastSquaresOptim.jl-master\test\nonlinearsolvers.jl, in expression starting on line 505
while loading C:\Users\Denis\Documents\Finmod\Schumann Bischoff\LeastSquaresOptim.jl-master\test\runtests.jl, in expression starting on line 7
while loading In[1], in expression starting on line 1

And nonlinearleastsquares.jl:

LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{LeastSquaresOptim.Dogleg{Tx1,Tx2,Tx3,Tx4,Ty1,Ty2}})
This may have arisen from a call to the constructor LeastSquaresOptim.Dogleg{Tx1,Tx2,Tx3,Tx4,Ty1,Ty2}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  convert{T}(::Type{T}, !Matched::T)
  LeastSquaresOptim.Dogleg{Tx1,Tx2,Tx3,Tx4,Ty1,Ty2}(, !Matched::Tx1, !Matched::Tx2, !Matched::Tx3, !Matched::Tx4, !Matched::Ty1, !Matched::Ty2)
  call{T}(::Type{T}, !Matched::Any)
while loading C:\Users\Denis\Documents\Finmod\Schumann Bischoff\LeastSquaresOptim.jl-master\test\nonlinearleastsquares.jl, in expression starting on line 92
while loading In[1], in expression starting on line 1

 [inlined code] from C:\Users\Denis\Documents\Finmod\Schumann Bischoff\LeastSquaresOptim.jl-master\test\nonlinearleastsquares.jl:93
 in anonymous at no file:0
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320

More generally, it would be nice to demo the simple example (Rodenbrock) with all the possible combinations of cases: dense, sparse, LM and Dogleg. To compare with pysparseLM then it would be Chol, LM.

Thanks

**Comment by matthieugomez** [comment]
Hi. Yeah I'll develop the readme. 
About the tests, they work on travis
https://travis-ci.org/matthieugomez/LeastSquaresOptim.jl
Can you try `Pkg.checkout` to make sure you have the latest version?

**Comment by finmod** [comment]
Thank you for your prompt attention. 

Pkg.checkout(“LeastSquaresOptim”) did it even though the output said that it did not do anything.

Runtests.jl answers all my questions about efficiency.
