### ISSUE TITLE
BigFloat support?

### ISSUE THREAD

**Issue by jherekhealy** [matthieugomez/LeastSquaresOptim.jl#32]
I tried to solve a system of BigFloat, and it broke due to typing in dense_qr.jl line 48.
```julia
    u = zeros(length(nls.y) + length(nls.x))
```
does not specify the type, 
```julia
    u = zeros(typeof(nls.y), length(nls.y) + length(nls.x))
```
would help here, although it may break later on.

In any case, congrats on this solver. It is robust, fast, usually converges faster than the alternatives such as minpack.

**Comment by matthieugomez** [comment]
Thanks!
Should be solved by https://github.com/matthieugomez/LeastSquaresOptim.jl/commit/538b4e319444754f887fc6d62e60df6d3ff71eef
Please reopen with a MWE if not
