### ISSUE TITLE
Warning about type `T` declared but not used

### ISSUE THREAD

**Issue by GlenHertz** [matthieugomez/LeastSquaresOptim.jl#34]
Perhaps minor issue, I get the warning:

```
WARNING: method definition for mul! at .../LeastSquaresOptim/B1WKJ/src/solver/iterative_lsmr.jl:87 declares type variable T but does not use it.
```

When `using` a package that depends on this package.

**Comment by GlenHertz** [comment]
Is there a reason to have this unused type:
https://github.com/matthieugomez/LeastSquaresOptim.jl/blob/c8dc7f7c1f0d4e4fcae215be0b7e385ffcfd81c4/src/solver/iterative_lsmr.jl#L87

**Comment by matthieugomez** [comment]
Thanks! Should be fixed now.
