### ISSUE TITLE
lower/upper bound does not really work

### ISSUE THREAD

**Issue by jherekhealy** [matthieugomez/LeastSquaresOptim.jl#35]
`optimize(rosenbrock, [0.0,0.0], LevenbergMarquardt(), autodiff=:forward,upper = fill(0.75, length(x0)))`

Results of Optimization Algorithm
 * Algorithm: LevenbergMarquardt
 * Minimizer: [0.75,0.75]
 * Sum of squares at Minimum: 351.625000
 * Iterations: 39
 * Convergence: true
 * |x - x'| < 1.0e-08: false
 * |f(x) - f(x')| / |f(x)| < 1.0e-08: true
 * |g(x)| < 1.0e-08: false
 * Function Calls: 40
 * Gradient Calls: 34
 * Multiplication Calls: 117

At the initial point, the value is 1.0 and clearly lower. Granted, it may be challenging to find the proper minimum. But 0.75,0.75 is very far off.

**Comment by matthieugomez** [comment]
Thanks. This PR https://github.com/matthieugomez/LeastSquaresOptim.jl/pull/36 seems to solve this issue
