### ISSUE TITLE
LeastSquaresOptim: is Autodiff an option or just a test

### ISSUE THREAD

**Issue by finmod** [matthieugomez/LeastSquaresOptim.jl#8]
Matthieu,

Testing LeastSquaresOptim inside DifferentialEquations @ChrisRackauckas , I am glad to report that everything works fine following the guidance of your READ.ME. 
However, running Pkg.test("LeastSquaresOptim") I notice that you are testing for Autodiff for dl and lm. Is it available as an option and should it appear in the READ.ME or is it just a test?

Also, it would be nice in your standard printing/reporting to print exec time, memory allocation and gc time. As the examples grow in size and complexity, this would allow the user to pick the most efficient combinations of options.  There is also the question of a restart facility with shuffling of starting values to eliminate local minima.

**Comment by matthieugomez** [comment]
The autodiff mentions in the tests refer to forwarddiff, which is explained in the README.
